config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'

  devise_for :users, :controllers => {:registrations => "registrations"}
  # devise_for :views
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # get 'sessions/new'
  # get 'users' => "orders#new"
  # resources :sessions
  resources :users
  resources :products
  resources :orders
  # resources :logins

  root :to => "home#index"

# resources :odrder_products
# resources :categories
# resources :users do
# resources :orders do
# resources :products
# end
# end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :product
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/odrder_product.rb
class OdrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index

    if user_signed_in?

          # redirect_to  rails_admin.dashboard_path
          redirect_to   orders_path
    else
      redirect_to    new_user_session_path
    end
end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

def index
@logins = Login.all
end



def new
end






end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: current_user)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
        @orders = Order.where(user_id: current_user)
  end

  # GET /orders/new
  def new
    # @user = User.find(params[:user_id])
    @order = current_user.orders.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    # @user = User.find(params[:user_id])
    @order = current_user.orders.build(order_params)

    # respond_to do |format|
      if @order.save
       redirect_to @order

      else
        render 'new'
      end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:orderdate, :notes, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :category)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to new_view_session 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :ext, :room_no, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/odrder_products_helper.rb
module OdrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :orderdate %>
    <%= f.datetime_select :orderdate %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Orderdate</th>
      <th>Notes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status %></td>
        <td><%= order.orderdate %></td>
        <td><%= order.notes %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %> -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8">
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Home</title>
  <!-- ============ Google fonts ============ -->
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
  type='text/css' />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
  rel='stylesheet' type='text/css' />
  <!-- ============ Add custom CSS here ============ -->
  <link href="../assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <link href="../assets/css/style.css" rel="stylesheet" type="text/css" />
  <link href="../assets/css/font-awesome.css" rel="stylesheet" type="text/css" />
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="../assets/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="color">
    <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
      <div class="container">
        <div class="navbar-header"><a class="navbar-brand" href="#">Home Cafe</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
          <ul class="nav navbar-nav navbar-right menu">
            <!-- <li><a href="">Home</a></li> -->
            <li><%= link_to "Home", new_order_path %></li>
            <li><%= link_to "My Orders", orders_url %></li>

        </ul>
        </div>
      </div>
    </div>

<div class="container">
  <h2 class="myorder">My Orders</h2>
  <div class="col-xs-12 date">
    <span>From: </span>
    <input type="date" name="" class="date_from" value="">
    <span>To: </span>
    <input type="date" name="" class="date_to" value="">
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Order date</th>
        <th>Status</th>
        <th>Amount</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.orderdate %></td>
          <td><%= order.status %></td>
          <td><%= order.notes %></td>
          <td><%= order.user %></td>
          <td><%= link_to 'Show', order %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</body>
</html>

app/views/orders/new.html.erb
<!-- <h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %> -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8">
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Home</title>
  <!-- ============ Google fonts ============ -->
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
  type='text/css' />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
  rel='stylesheet' type='text/css' />
  <!-- ============ Add custom CSS here ============ -->
  <!-- <link href="../assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" /> -->
  <!-- <link href="../assets/css/style.css" rel="stylesheet" type="text/css" /> -->
  <!-- <link href="../assets/css/font-awesome.css" rel="stylesheet" type="text/css" /> -->
  <%= stylesheet_link_tag("/assets/css/bootstrap.min.css") %>
  <%= stylesheet_link_tag("/assets/css/font-awesome.css") %>
  <%= stylesheet_link_tag("/assets/css/style.css") %>

  <!-- <%= stylesheet_link_tag("/assets/js/bootstrap.min.css") %>
  <%= stylesheet_link_tag("/assets/js/font-awesome.css") %>
  <%= stylesheet_link_tag("/assets/js/style.css") %> -->
</head>
<body>
  <div class="color">
    <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
      <div class="container">
        <div class="navbar-header"><a class="navbar-brand" href="#">Home Cafe</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
          <ul class="nav navbar-nav navbar-right menu">
            <li><a href="home.html">Home</a></li>
            <!-- <li><a href="myorders.html">My Orders</a></li> -->
            <li><%= link_to "My Orders", orders_url %></li>

            <li><span>Aboubakr Khedr</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="col-xs-12">
        <div class="col-md-4 order">
          <h5>Order Items</h5>
          <ul>
            <li id="1">
              <span class="product">Tea</span>
              <input type="text" name="num_q" value="1" class="num_q form-control input-form">
              <span class="plus-span">
                <i class="fa fa-plus plus" aria-hidden="true"></i>
                <i class="fa fa-minus" aria-hidden="true"></i>
              </span>
              <input type="hidden" class="basic_price" name="basic_price" value="25">
              <span class="price">25 LE.</span>
              <span class="delete"><i class="fa fa-times" aria-hidden="true"></i></span>
            </li>
            <li id="2">
              <span class="product">Coffee</span>
              <input type="text" name="num_q" value="1" class="num_q form-control input-form">
              <span class="plus-span">
                <i class="fa fa-plus plus" aria-hidden="true"></i>
                <i class="fa fa-minus" aria-hidden="true"></i>
              </span>
              <input type="hidden" class="basic_price" name="basic_price" value="40">
              <span class="price">40 LE.</span>
              <span class="delete"><i class="fa fa-times" aria-hidden="true"></i></span>
            </li>
          </ul>
          <div class="col-xs-12 note">
            <h4>Notes</h4>
            <textarea name="name" class="form-control input-form" rows="3" cols="37"></textarea>
          </div>
          <div class="col-xs-12 room">
            <h4>Room No.</h4>
            <select class="room_no form-control  input-form" name="">
              <option value="">2005</option>
              <option value="">2006</option>
              <option value="">2007</option>
            </select>
          </div>
          <div class="total">
            <span>55 LE.</span>
          </div>
          <div class="col-xs-12">
            <input type="submit" name="" class="btn btn-primary confirm" value="Confirm">
          </div>
        </div>
        <div class="col-md-8">
          <div class="col-xs-12">
            <div class="col-xs-6"></div>
            <div class="col-md-6">
                <form action="" class="search-form">
                    <div class="form-group has-feedback">
                    <label for="search" class="sr-only">Search</label>
                    <input type="text" class="form-control" name="search" id="search" >
                      <span class="glyphicon glyphicon-search form-control-feedback"></span>
                  </div>
                </form>
            </div>
          </div>
          <div class="col-xs-12 last_order">
            <div class="col-xs-12">
              <h3>Lastest Order</h3>
            </div>
            <div class="col-xs-3">
              <a href="detail_page.html" class="strip_list">
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant.jpg" alt="">
                  </div>
                  <h5>Green Tea</h5>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
            <div class="col-xs-3">
              <a href="detail_page.html" class="strip_list">
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant.jpg" alt="">
                  </div>
                  <h5>Green Tea</h5>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
            <div class="col-xs-3">
              <a href="detail_page.html" class="strip_list">
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant.jpg" alt="">
                  </div>
                  <h5>Green Tea</h5>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
            <div class="col-xs-3">
              <a href="detail_page.html" class="strip_list">
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant.jpg" alt="">
                  </div>
                  <h5>Green Tea</h5>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
          </div>
          <div class="col-xs-12 av_item">
                <h4>Available Items</h4>
            <div class="col-xs-3">
              <a class="strip_list">
                <div class="price_av"><span>60 LE</span></div>
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant_6.jpg" alt="">
                  </div>
                  <h5>Green Tea</h5>
                  <span class="add_to_order" id="1">Add+</span>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
            <div class="col-xs-3">
              <a class="strip_list">
                <div class="price_av"><span>90 LE</span></div>
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant_6.jpg" alt="">
                  </div>
                  <h5>Green Tea</h5>
                  <span class="add_to_order" id="2">Add+</span>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
            <div class="col-xs-3">
              <a class="strip_list">
                <div class="price_av"><span>20 LE</span></div>
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant_6.jpg" alt="">
                  </div>
                  <h5>Black Tea</h5>
                  <span class="add_to_order" id="3">Add+</span>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
            <div class="col-xs-3">
              <a class="strip_list">
                <div class="price_av"><span>40 LE</span></div>
                <div class="desc">
                  <div class="thumb_strip">
                    <img src="http://www.ansonika.com/quickfood/img/thumb_restaurant_6.jpg" alt="">
                  </div>
                  <h5>Nescafe</h5>
                  <span class="add_to_order" id="4">Add+</span>
                </div><!-- End desc-->
              </a><!-- End strip_list-->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
$(document).on("click", ".plus", function(event){
  var input = $(this).closest('span').prev('input')[0];
  var price_order = $(this).closest('span').next('input')[0].value;
  var elem = input.value
  var val = ++elem;
  var price_fin = price_order*val
  $(this).closest('span').prev('input')[0].value = val;
  $(this).closest('span').nextAll(".price")[0].textContent = price_fin+" LE.";
});

$(document).on("click", ".fa-minus", function(event){
  var input = $(this).closest('span').prev('input')[0];
  var price_order = $(this).closest('span').next('input')[0].value;
  var elem = input.value
  if(elem > 1){
    var val = --elem;
    var price_fin = price_order*val
    $(this).closest('span').prev('input')[0].value = val;
    $(this).closest('span').nextAll(".price")[0].textContent = price_fin+" LE.";
  }
});

$(document).on("click", ".add_to_order", function(event){
  var input = $(this).prev('h5')[0].textContent;
  var price = $(this).closest("div").prev('.price_av')[0].textContent;
  var id_pro = $(this).attr('id');
  var li = '<li id="'+id_pro+'"><span class="product">'+input+'</span>\
          <input type="text" name="num_q" value="1" class="num_q form-control input-form">\
            <span class="plus-span">\
              <i class="fa fa-plus plus" aria-hidden="true"></i>\
              <i class="fa fa-minus" aria-hidden="true"></i>\
            </span>\
            <input type="hidden" class="basic_price" name="basic_price" value="'+price+'">\
            <span class="price">'+price+'</span>\
            <span class="delete"><i class="fa fa-times" aria-hidden="true"></i></span>\
          </li>';
  var flag = false;
$(function(){
  $(".order ul li").each(function(){
      var id = $(this).find('div.page#'+id_pro+'');
      if(id.context.id == id_pro){

        flag = true;
      }
  });
});
  if(!flag){
    $(".order ul").append(li);
  }
});

$(document).on("click", ".delete", function(event){
  $(this).context.parentElement.remove();
});

$("#search").on("keyup", function() {
  var g = $(this).val();
  $(".desc h5").each( function() {
    var s = $(this).text();
    console.log(s.indexOf(g));
    if (s.toLowerCase().search(g) >= 0) {
      $(this).parent().parent().show();
    }
    else {
      $(this).parent().parent().hide();
    }
  });
});
</script>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Orderdate:</strong>
  <%= @order.orderdate %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @order.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.category %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :ext %>
    <%= f.number_field :ext %>
  </div>

  <div class="field">
    <%= f.label :room_no %>
    <%= f.number_field :room_no %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ext</th>
      <th>Room no</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.ext %></td>
        <td><%= user.room_no %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Ext:</strong>
  <%= @user.ext %>
</p>

<p>
  <strong>Room no:</strong>
  <%= @user.room_no %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>